version: 1.9.alpha.{build}

init:
  - echo %path%
  - path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Mercurial;C:\Program Files\7-Zip;C:\Tools\xUnit;C:\Tools\NUnit\bin;C:\Tools\NuGet;C:\Python27;C:\Tools\WebDriver;C:\Tools\MSpec;C:\Program Files\Java\jdk1.7.0\bin;C:\ProgramData\chocolatey\bin;C:\Tools\GitVersion;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\CollabNet\Subversion Client;C:\Users\appveyor\AppData\Roaming\npm;C:\Ruby193\bin;C:\Program Files (x86)\CMake\bin;C:\go\bin;C:\Chocolatey\bin;C:\Program Files\AppVeyor\BuildAgent
  - mkdir %systemdrive%\OSGeo4w
  - cd %systemdrive%\OSGeo4w
  - ps: (new-object net.webclient).DownloadFile('http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe', 'osgeo4w-setup-x86_64.exe')
  - osgeo4w-setup-x86_64.exe --quiet-mode --upgrade-also --delete-orphans --no-desktop --advanced  --root %systemdrive%\OSGeo4w --packages msvcrt,setup,shell,avce00,zlib,iconv,libxml2,cairo,openssl,curl,expat,fcgi,ffmpeg,fftw,freexl,fribidi,libpng,libjpeg,libjpeg12,libtiff,libgeotiff,proj-hpgn,proj-datumgrid,proj,geos,libmysql,sqlite3,hdf5,netcdf,libpq,xerces-c-vc10,hdf4,ogdi,openjpeg,spatialite,gdal,python-core,python-numpy,gdal-python,gdal-autotest,gdal-filegdb,pdcurses,msys,python-win32,wxpython,python-pil,pyopengl,gs,gsl-libs,libspatialindex,mapserver,mapscript-python,msinttypes,opencv,psycopg2,qt4-libs,pyqt4,pyspatialite,six,python-dateutil,python-devel,python-help,sip,qscintilla,python-qscintilla,python-shapely,python-simplejson,python-tcltk,python-test,python-tools,python-xlrd,python-xlwt,qwt5-libs-qt4,setuptools --site http://download.osgeo.org/osgeo4w
  - cd %APPVEYOR_BUILD_FOLDER%

build: off

test_script:
  - cd osm2ma
  - echo %path%
  - '%systemdrive%\OSGeo4w\OSGeo4W.bat echo %path%'
  - '%systemdrive%\OSGeo4w\OSGeo4W.bat o-help'
  - '%systemdrive%\OSGeo4w\OSGeo4W.bat python tests.py' 
  - '%systemdrive%\OSGeo4w\OSGeo4W.bat python -m unittest discover -s osm2ma' 
branches:
  only:
  - test/appvey-config
