version: 1.9.alpha.{build}

init:
  - mkdir %systemdrive%\OSGeo4w
  - pushd %systemdrive%\OSGeo4w
  - ps: (new-object net.webclient).DownloadFile('http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe', 'osgeo4w-setup-x86_64.exe')
  - osgeo4w-setup-x86_64.exe --quiet-mode --upgrade-also --delete-orphans --no-desktop --advanced  --root %systemdrive%\OSGeo4w --download --packages qgis,gis-globe-plugin,qgis-grass-plugin,gdal,gdal-ecw,gdal-mrsid,gdal-filegdb,gdal-python,gdal-autotest,python-core,python-help,python-tcltk,python-tools,python-dateutil,python-devel,python-numpy,python-pil,python-shapely,python-simplejson,python-test,python-win32,python-xlrd,python-xlwt,wxpython,setup,setuptools,shell,msys,gs,curl,geos,gsl,libgeotiff,libjpeg,libjpeg12,libspatialindex,libtiff,msvcrt,openssl,proj,openjpeg,ffmpeg,msinttypes,opencv,cairo,avce00,expat,fftw,freexl,grass,gsl-libs,hdf4,hdf5,iconv,libmysql,libpng,libpq,libxml2,netcdf,ogdi,pdcurses,proj-datumgrid,proj-hpgn,psycopg2,pyopengl,pyqt4,pyspatialite,python-qscintilla,qgis-common,qscintilla,qt4-libs,qwt5-libs-qt4,sip,six,spatialite,sqlite3,szip,xerces-c-vc10,zlib,mapscript-python,mapserver,qgis-server,fcgi,fribidi,apache,apache-manual,freetype-mingw,gdal15dll,gdal18dll,gdal19dll,libcairo,libintl,mod_fcgid,msys-grass,php,python,python-testsuite,spatialite3dll,mapnik,openlayers,tcltk,xerces-c,xerces-c-vc9,mapserver56
  - popd

build: off

test_script:
  - cd osm2ma
  - '%systemdrive%\OSGeo4w\OSGeo4W.bat python osm2mapaction.py'
